// Purpose: Header for tff_team_entity
// Boilerplate generated by ModMaker on 23/05/2018 08:03:45
/* base for team allied entities*/

#ifndef TFF_TEAM_ENT
#define TFF_TEAM_ENT

class CTffTeamCore
{
public:
	virtual CBaseEntity * GetBaseEntity() { return NULL; };

	void SetTeamNumber(inputdata_t& inputdata); /* Specify the team number to change to */

	// outputs
	COutputEvent m_OnTeamSet; /* Fired when my team is set */

	virtual void ChangeTeam(int teamNumber);

	virtual bool IsAlly(CBaseEntity * pOther);
	virtual bool IsEnemy(CBaseEntity * pOther);
	virtual bool IsOnRealTeam(CBaseEntity * pOther);
};

#define TEAM_CORE () \
virtual void SetTeamNumber(inputdata_t& inputdata){ CTffTeamCore::SetTeamNumber(inputdata); } ; /* Specify the team number to change to */ \
virtual void ChangeTeam(int teamNumber){ CTffTeamCore::ChangeTeam(teamNumber); }; \
virtual CBaseEntity * GetBaseEntity() { return this; };

class CTffTeamEntity : public CBaseEntity , CTffTeamCore
{
public:
    DECLARE_CLASS( CTffTeamEntity, CBaseEntity );

	TEAM_CORE();

    DECLARE_DATADESC();
};

#endif // TFF_TEAM_ENT