// Purpose: Header for tff_payload
// Boilerplate generated by ModMaker on 23/05/2018 07:50:15
/* Payload on train*/

#include "tff_team_entity.h"

class CTffPayload : public CBaseAnimating, CTffTeamCore // Angles, Targetname, BaseTrain, Studiomodel
{
public:
    DECLARE_CLASS( CTffPayload, CBaseAnimating);

    Vector   m_vecCameraOffset;
    string_t m_iStartSound;
    string_t m_iMoveSound;
    string_t m_iStopSound;
    string_t m_iPathStartEntity;
	float    m_fEffectRadius;

    virtual void Precache();
    virtual void Spawn();

    // outputs
    COutputEvent m_OnFirstMove; /* Payload started moving */
    COutputEvent m_OnStop; /* Payload stopped */
    COutputEvent m_OnFullSpeed; /* Payload reached full speed */
    COutputEvent m_OnCrossedWaypoint; /* Payload crossed a waypoint */
    COutputEvent m_OnEnteredEnemyBase; /* Payload entered the enemy base */

	TEAM_CORE();

	void TrainThink();
	void TrainCheckPlayers();
	void TrainStop();

    DECLARE_DATADESC();

private:
	enum move_speed
	{
		STOPPED,
		SLOW,
		MOVING,
		RUNNING
	};

	bool m_bHasMoved;
	move_speed m_eMoveSpeed;
	float m_fMaxSpeed;
	Vector m_vNextPath;


	int m_iAllies;
	int m_iWoundedAllies;
	int m_iLowAmmoAllies;
	int m_iEnemies;

	CBasePlayer * m_woundedAllies[MAX_PLAYERS];
	CBasePlayer * m_lowAmmoAllies[MAX_PLAYERS];
};
