// Purpose: Header for tff_payload_path_terminus
// Boilerplate generated by ModMaker on 23/05/2018 07:51:28
/* */
#include "tff_base_payload_path.h"

class CTffPayloadPathTerminus : public CTffBasePayloadPath
{
public:
    DECLARE_CLASS( CTffPayloadPathTerminus, CTffBasePayloadPath);


    DECLARE_DATADESC();
};
