// Purpose: Body for tff_payload_path_veer_right
// Boilerplate generated by ModMaker on 23/05/2018 07:51:48
/* */

#include "cbase.h"
#include "tff_payload_path_veer_right.h"

// memdbgon must be the last include file in a .cpp file!!!
#include "tier0/memdbgon.h"

LINK_ENTITY_TO_CLASS( tff_payload_path_veer_right, CTffPayloadPathVeerRight );

BEGIN_DATADESC( CTffPayloadPathVeerRight )
END_DATADESC()
