// Purpose: Body for tff_payload_path_ramp_up
// Boilerplate generated by ModMaker on 23/05/2018 07:50:53
/* */

#include "cbase.h"
#include "tff_payload_path_ramp_up.h"

// memdbgon must be the last include file in a .cpp file!!!
#include "tier0/memdbgon.h"

LINK_ENTITY_TO_CLASS( tff_payload_path_ramp_up, CTffPayloadPathRampUp );

BEGIN_DATADESC( CTffPayloadPathRampUp )
END_DATADESC()
