// Purpose: Header for tff_flag_point
// Boilerplate generated by ModMaker on 23/05/2018 07:49:49
/* */
#include "tff_team_entity.h"

class CTffFlagPoint : public CBaseEntity, CTffTeamCore // Studiomodel, Targetname, Inputfilter
{
public:
    DECLARE_CLASS( CTffFlagPoint, CBaseEntity );

    int      m_iRadius;
	Vector   m_vecCameraOffset;

	//secret inputs (for loose class binding)
	void Taken(inputdata_t& inputdata);
	void ReturnFlag(inputdata_t& inputdata);

    // outputs
    COutputEvent m_OnFlagTaken; /* Fired when Flag was Taken */
    COutputEvent m_OnFlagReturned; /* Fired when Flag was Returned */

	TEAM_CORE();

    DECLARE_DATADESC();
};
