// Purpose: Header for tff_payload_path_waypoint
// Boilerplate generated by ModMaker on 23/05/2018 07:51:59
/* */

#include "tff_base_payload_path.h"

class CTffPayloadPathWaypoint : public CTffBasePayloadPath
{
public:
    DECLARE_CLASS( CTffPayloadPathWaypoint, CTffBasePayloadPath);

    DECLARE_DATADESC();
};
