// Purpose: Header for tff_team_base
// Boilerplate generated by ModMaker on 23/05/2018 07:43:53
/* */

#include "tff_team_entity.h"
#include "triggers.h"

class CTffTeamBase : public CBaseTrigger, CTffTeamCore // tff_team_entity, Targetname, BaseBrush
{
public:
    DECLARE_CLASS( CTffTeamBase, CBaseTrigger);

	TEAM_CORE();

    DECLARE_DATADESC();

	virtual void Spawn();
};
