// Purpose: Header for tff_flag
// Boilerplate generated by ModMaker on 23/05/2018 07:44:27
/* Carryable player item and objective for the Old Freebie mode*/

#include "tff_team_entity.h"
#include "items.h"

class CTffFlag : public CItem, CTffTeamCore // tff_team_entity, Studiomodel, Targetname
{
public:
    DECLARE_CLASS( CTffFlag, CItem);

	enum TFF_Flag_State
	{
		UNKNOWN,
		ON_POINT,
		CARRIED,
		DROPPED
	};

    int      m_iReturnTime;
	string_t m_iFlagPointEntity;

    // outputs
    COutputEvent m_OnPickedUp;
    COutputEvent m_OnLeftHomeBase;
    COutputEvent m_OnEnteredEnemyBase;
    COutputEvent m_OnDropped;
    COutputEvent m_OnReturned;

	TEAM_CORE();

    DECLARE_DATADESC();

	//Item overrides
	virtual void Precache();
	virtual void Spawn();
	virtual void ItemTouch(CBaseEntity *pOther);
private:
	virtual void SetState(TFF_Flag_State state, CBaseEntity * Setter);

	TFF_Flag_State m_eState;
	EHANDLE        m_eCarrier;
	EHANDLE        m_eFlagPoint;
};
