// Purpose: Body for tff_payload_path_veer_left
// Boilerplate generated by ModMaker on 23/05/2018 07:51:41
/* */

#include "cbase.h"
#include "tff_payload_path_veer_left.h"

// memdbgon must be the last include file in a .cpp file!!!
#include "tier0/memdbgon.h"

LINK_ENTITY_TO_CLASS( tff_payload_path_veer_left, CTffPayloadPathVeerLeft );

BEGIN_DATADESC( CTffPayloadPathVeerLeft )
END_DATADESC()
