// Purpose: Header for tff_payload_path_ramp_down
// Boilerplate generated by ModMaker on 23/05/2018 07:50:46
/* */
#include "tff_base_payload_path.h"

class CTffPayloadPathRampDown : public CTffBasePayloadPath
{
public:
    DECLARE_CLASS( CTffPayloadPathRampDown, CTffBasePayloadPath);


    DECLARE_DATADESC();
};
