// Purpose: Header for tff_payload_path_curve_left
// Boilerplate generated by ModMaker on 23/05/2018 07:50:25
/* */
#include "tff_base_payload_path.h"


class CTffPayloadPathCurveLeft : public CTffBasePayloadPath
{
public:
    DECLARE_CLASS( CTffPayloadPathCurveLeft, CTffBasePayloadPath);


    DECLARE_DATADESC();
};
