// Purpose: Body for tff_payload_path_start
// Boilerplate generated by ModMaker on 23/05/2018 07:51:04
/* */

#include "cbase.h"
#include "tff_payload_path_start.h"

// memdbgon must be the last include file in a .cpp file!!!
#include "tier0/memdbgon.h"

LINK_ENTITY_TO_CLASS( tff_payload_path_start, CTffPayloadPathStart );

BEGIN_DATADESC( CTffPayloadPathStart )
END_DATADESC()
