// Purpose: Header for tff_payload_path_veer_left
// Boilerplate generated by ModMaker on 23/05/2018 07:51:41
/* */
#include "tff_base_payload_path.h"

class CTffPayloadPathVeerLeft : public CTffBasePayloadPath 
{
public:
    DECLARE_CLASS( CTffPayloadPathVeerLeft, CTffBasePayloadPath);


    DECLARE_DATADESC();
};
