// Purpose: Header for tff_pickup
// Boilerplate generated by ModMaker on 23/05/2018 07:52:08
/* pickup a random item*/

class CTffPickup : public CBaseEntity // Inputfilter
{
public:
    DECLARE_CLASS( CTffPickup, CBaseEntity );

    int      m_iSpawnRate;
    string_t m_iSpawnSound;

    virtual void Precache();
    virtual void Spawn();
	virtual void RespawnItemThink();

    // outputs
    COutputEvent m_OnSpawnItem;
    COutputEvent m_OnItemPickup;

	//
	void OnItemPickup(inputdata_t& inputdata);

    DECLARE_DATADESC();
private:
	EHANDLE m_spawned_item;
};
