// Purpose: Header for tff_payload_path_curve_right
// Boilerplate generated by ModMaker on 23/05/2018 07:50:39
/* */
#include "tff_base_payload_path.h"

class CTffPayloadPathCurveRight : public CTffBasePayloadPath
{
public:
    DECLARE_CLASS( CTffPayloadPathCurveRight, CTffBasePayloadPath);


    DECLARE_DATADESC();
};
