// Purpose: Body for tff_payload_path_curve_left
// Boilerplate generated by ModMaker on 23/05/2018 07:50:25
/* */

#include "cbase.h"
#include "tff_payload_path_curve_left.h"

// memdbgon must be the last include file in a .cpp file!!!
#include "tier0/memdbgon.h"

LINK_ENTITY_TO_CLASS( tff_payload_path_curve_left, CTffPayloadPathCurveLeft );

BEGIN_DATADESC( CTffPayloadPathCurveLeft )
END_DATADESC()
