// Purpose: Body for tff_team_base
// Boilerplate generated by ModMaker on 23/05/2018 07:43:53
/* */

#include "cbase.h"
#include "tff_team_base.h"

// memdbgon must be the last include file in a .cpp file!!!
#include "tier0/memdbgon.h"

BEGIN_DATADESC( CTffTeamBase )
END_DATADESC()

LINK_ENTITY_TO_CLASS(tff_team_base, CTffTeamBase);

void CTffTeamBase::Spawn()
{
	BaseClass::Spawn();

	ICollideable * collides = CBaseTrigger::GetCollideable();

	if (collides == NULL) return;

	//Get our bounding box
	Vector vecMins;
	Vector vecMaxs;
	collides->WorldSpaceTriggerBounds(&vecMins, &vecMaxs);
	
	//Get the entities inside our bounding box
	CBaseEntity *list[1024];
	int count = UTIL_EntitiesInBox(list, 1024, vecMins, vecMaxs, 0);

	if (count == 0) return;

	for (int index = 0; index < count; index++)
	{
		if ( !PointIsWithin( list[index]->GetAbsOrigin() ) ) continue; //the entity is within our bounding box, but not within our "model"

		list[index]->ChangeTeam(GetTeamNumber()); //inside me? then you're on my team /*CTffTeamEntity::*/
	}
}

//TODO add onTouch events to notify payloads/flags entering me