// Purpose: Header for tff_payload_path_start
// Boilerplate generated by ModMaker on 23/05/2018 07:51:04
/* */
#include "tff_base_payload_path.h"

class CTffPayloadPathStart : public CTffBasePayloadPath
{
public:
    DECLARE_CLASS( CTffPayloadPathStart, CTffBasePayloadPath);


    DECLARE_DATADESC();
};
