// Purpose: Header for tff_base_payload_path
// Boilerplate generated by ModMaker on 23/05/2018 08:00:01

#include "tff_team_entity.h"

class CTffBasePayloadPath : public CBaseEntity, CTffTeamCore // tff_team_entity, Angles, Targetname
{
public:
    DECLARE_CLASS( CTffBasePayloadPath, CBaseEntity);

    string_t m_iModel;
    string_t m_iNextPathEntity;
    int      m_iSpeed;

    virtual void Precache();
    virtual void Spawn();

    // outputs
    COutputEvent m_OnPayloadPassed;

	TEAM_CORE();

    DECLARE_DATADESC();

	virtual void PayloadPassed(CBaseEntity * pPlayload, int& speed, string_t& nextPath);
};
