// Purpose: Header for tff_rules
// Boilerplate generated by ModMaker on 23/05/2018 07:53:00
/* Game Rules and Timer for TFF*/

#include "entityoutput.h"

enum game_phase
{
	Lobby,
	Setup,
	Playing,
	Intermission
};

class CTffRules : public CBaseEntity // Targetname
{
public:
    DECLARE_CLASS( CTffRules, CBaseEntity );

    int      m_iSetupTime;
    int      m_iTimeout;
	int      m_iMode;

    // input handlers
    void SetTimeout( inputdata_t& inputdata ); /* Sets the round timeout in seconds */
    void AddTime( inputdata_t& inputdata ); /* Delays the end of the round */
    void RemoveTime( inputdata_t& inputdata ); /* Shortems the round */
    void ForceTimeout( inputdata_t& inputdata ); /* Timeout right now */

    // outputs
    COutputEvent m_OnSetupEnded;
    COutputEvent m_OnTimeout;

    DECLARE_DATADESC();

	void SetPhase(game_phase NewPhase);
	game_phase GetPhase();
private:
	float m_fTimeOut;
	game_phase m_phase;

	void CheckTimeout();
	void SetupEndThink();
	void TimeoutThink();
};
