// Purpose: Body for tff_payload_path_curve_right
// Boilerplate generated by ModMaker on 23/05/2018 07:50:39
/* */

#include "cbase.h"
#include "tff_payload_path_curve_right.h"

// memdbgon must be the last include file in a .cpp file!!!
#include "tier0/memdbgon.h"

LINK_ENTITY_TO_CLASS( tff_payload_path_curve_right, CTffPayloadPathCurveRight );

BEGIN_DATADESC( CTffPayloadPathCurveRight )
END_DATADESC()
