// Purpose: Header for tff_payload_path_straight
// Boilerplate generated by ModMaker on 23/05/2018 07:51:19
/* */
#include "tff_base_payload_path.h"

class CTffPayloadPathStraight : public CTffBasePayloadPath
{
public:
    DECLARE_CLASS( CTffPayloadPathStraight, CTffBasePayloadPath);


    DECLARE_DATADESC();
};
