// Purpose: Body for tff_payload_path_ramp_down
// Boilerplate generated by ModMaker on 23/05/2018 07:50:46
/* */

#include "cbase.h"
#include "tff_payload_path_ramp_down.h"

// memdbgon must be the last include file in a .cpp file!!!
#include "tier0/memdbgon.h"

LINK_ENTITY_TO_CLASS( tff_payload_path_ramp_down, CTffPayloadPathRampDown );

BEGIN_DATADESC( CTffPayloadPathRampDown )
END_DATADESC()
