// Purpose: Header for tff_payload_path_ramp_up
// Boilerplate generated by ModMaker on 23/05/2018 07:50:53
/* */
#include "tff_base_payload_path.h"

class CTffPayloadPathRampUp : public CTffBasePayloadPath
{
public:
    DECLARE_CLASS( CTffPayloadPathRampUp, CTffBasePayloadPath);


    DECLARE_DATADESC();
};
